name: Build installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Set VS.NET environment
        run: |
          cmd.exe /C CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Build VSTO
        run: |
          msbuild SafeExamBrowser.sln /p:Platform="x64" /p:Configuration="Release" /p:VisualStudioVersion="17.0" /nr:false /nodeReuse:false

      - name: Build installer
        run: |
          devenv.exe .\unsafe_installer\unsafe_installer.vdproj /build "Release|x64"
        working-directory: .\unsafe_installer
