name: Build installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Set VS.NET environment
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64

      - name: Build VSTO
        run: |
          msbuild SafeExamBrowser.sln /p:Platform="x64" /p:Configuration="Release" /p:VisualStudioVersion="17.0" /nr:false /nodeReuse:false

      - name: Build installer
        run: |
          devenv.exe .\unsafe_installer\unsafe_installer.vdproj /build "Release|x64"
        working-directory: .\unsafe_installer
