name: Build installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore SafeExamBrowser.sln

      - name: Set VS.NET environment
        run: |
          cmd.exe /C CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Enable .vdproj Builds
        working-directory: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild'
        run: |
          & '.\DisableOutOfProcBuild.exe'

      - name: Build VSTO
        run: |
          msbuild SafeExamBrowser.sln /p:Platform="x64" /p:Configuration="Release" /p:VisualStudioVersion="17.0" /nr:false /nodeReuse:false

      - name: Build installer
        run: |
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com' .\unsafe_installer\unsafe_installer.vdproj /build "Release|x64"

      - name: Download vc_redist
        run: |
          Invoke-WebRequest -OutFile ./unsafe_installer/Release/vc_redist.x64.exe https://aka.ms/vs/17/release/vc_redist.x64.exe

      - name: Create leesmij.txt
        run: |
          Set-Content ./unsafe_installer/Release/leemij.txt 'Installeer unsafeexambrowser.msi en VC_redist.x64.exe.`nHet maakt niet uit in welke volgorde.'

      - name: Create leesmij.txt
        run: |
          Remove-Item ./unsafe_installer/Release/setup.exe

      - name: Create Zip file
        run: |
          Compress-Archive -Path ./unsafe_installer/Release/* -DestinationPath ./unsafe_installer/Release/unsafeexambrowser.zip

      - name: Upload installer
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./unsafe_installer/Release/unsafeexambrowser.zip"
          allowUpdates: true
          tag: "2.0.0"
