name: Build installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore SafeExamBrowser.sln

      - name: Set VS.NET environment
        run: |
          cmd.exe /C CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Enable .vdproj Builds
        working-directory: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild'
        run: |
          & '.\DisableOutOfProcBuild.exe'

      - name: Build VSTO
        run: |
          msbuild SafeExamBrowser.sln /p:Platform="x64" /p:Configuration="Release" /p:VisualStudioVersion="17.0" /nr:false /nodeReuse:false

      - name: Build installer
        run: |
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com' .\unsafe_installer\unsafe_installer.vdproj /rebuild "Release|x64"

      - name: Waiting for installer file in the background
        id: wait-for-msi
        run: |
          $timeoutMinutes = 10
          $startTime = Get-Date
          $msiFilePath = "./unsafe_installer/Release/unsafeexambrowser.msi"
  
          while ((Get-Date) -lt ($startTime).AddMinutes($timeoutMinutes)) {
            if (Test-Path $msiFilePath) {
              Write-Host "::set-output name=msi_file_found::true"
              break
            }
            Start-Sleep -Seconds 10  # Check every 10 seconds
          }
  
      - name: Check if the installer is build
        run: |
          if ("${{ steps.wait-for-msi.outputs.msi_file_found }}" -eq "true") {
            Write-Host "MSI file found!"
          } else {
            Write-Host "Timeout: MSI file not found within specified time."
            exit 1
          }

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: unsafeexambrowser.msi
          path: ./unsafe_installer/Release/unsafeexambrowser.msi
          if-no-files-found: warn
          overwrite: true
