name: Build installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore SafeExamBrowser.sln

      - name: Set VS.NET environment
        run: |
          cmd.exe /C CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Enable .vdproj Builds
        working-directory: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild'
        run: |
          & '.\DisableOutOfProcBuild.exe'

      - name: Build VSTO
        run: |
          msbuild SafeExamBrowser.sln /p:Platform="x64" /p:Configuration="Release" /p:VisualStudioVersion="17.0" /nr:false /nodeReuse:false

      - name: Build installer
        run: |
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe' .\unsafe_installer\unsafe_installer.vdproj /build "Release|x64"

      - uses: actions/checkout@master
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "/unsafe_installer/Release/unsafeexambrowser.msi"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
