name: Issue Maintenance
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          # https://github.com/marketplace/actions/close-stale-issues
          days-before-issue-stale: 28
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 28 days with no activity. It will soon be closed automatically if there are no updates."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-issue-labels: "bug,enhancement,feature request"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
